server:
  port: 8091

spring:
  application:
    name: accountservice
  datasource:
    url: jdbc:postgresql://localhost:5433/testdb
    username: testuser
    password: testuser
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        web: DEBUG
