---
name: Pipeline

on:
    push:
        branches:
            - main
    pull_request:

permissions:
    contents: read

jobs:
    conform:
        runs-on: ubuntu-latest
        name: Conform
        steps:
            - uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
              with:
                    egress-policy: audit
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                    fetch-depth: 0

    test:
        runs-on: ubuntu-latest
        name: Unit Tests
        strategy:
            max-parallel: 4
            matrix:
                java-version: ["21"]
        steps:
            - uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
              with:
                egress-policy: audit

            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                fetch-depth: 0

            - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
              with:
                java-version: "${{ matrix.java-version }}"
                distribution: "corretto"
            - uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0

            - run: ./gradlew test

    check:
        runs-on: ubuntu-latest
        name: Check Code
        strategy:
            max-parallel: 4
            matrix:
                java-version: ["21"]

        steps:
            - uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
              with:
                egress-policy: audit

            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                fetch-depth: 0

            - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
              with:
                java-version: "${{ matrix.java-version }}"
                distribution: "corretto"
            - uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0

            - run: ./gradlew check
              continue-on-error: true # Continue even if there are errors

    hadolint:
        runs-on: ubuntu-latest
        name: Lint Dockerfile

        steps:
        - uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
          with:
            egress-policy: audit

        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            fetch-depth: 0

        - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
          with:
            dockerfile: Dockerfile

    build:
        runs-on: ubuntu-latest
        name: Build Jar File
        needs:
            - test
            - check
        strategy:
            max-parallel: 4
            matrix:
                java-version: ["21"]

        steps:
            - uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
              with:
                egress-policy: audit

            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                fetch-depth: 0

            - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
              with:
                java-version: "${{ matrix.java-version }}"
                distribution: "corretto"
            - uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0

            - run: ./gradlew bootJar

            - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
              with:
                name: spring-boot-jar
                path: build/libs/accountservice.jar

    container:
        runs-on: ubuntu-latest
        name: Container
        needs:
            - build
            - hadolint
        permissions:
            contents: read
            packages: write

        steps:
            - uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
              with:
                egress-policy: audit

            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                fetch-depth: 0

            - uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
            - uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

            - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
              with:
                name: spring-boot-jar
                path: build/libs/

            - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
              with:
                context: .
                tags: ghcr.io/${{ github.repository }}:latest
                push: ${{ github.ref == 'refs/heads/main' }}
